### ISSUE TITLE
Cannot create Name, when providing empty namespace parameter, specific to Bubble

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#100]
Creating API calls on Bubble we have to provide all the possible  parameters, and the ones which are optional, there is an option to allow blank. Creating a local name where the namespace is left blank does not allow to create a name, gives the error namespace is blank.

Workaround now is using two API calls, one without the namespace parameter for local names and another with namespace parameter for namespaced names.

<img width="738" alt="Screenshot 2023-01-23 at 11 51 21 PM" src="https://user-images.githubusercontent.com/84140911/214119424-0a0a663c-8a6b-408f-9446-82f90dea99c5.png">

**Comment by VidereLicet** [comment]
This should be resolved with commit abb26aa113bd21e06e7e5b8a878cd975774bc868
