### ISSUE TITLE
[Mobile] "Cannot unlock while initializing dynamic indexing services: Check sessions/status/local"

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#105]
Calling 'sessions/unlock/local' right after logging in gives me `{"code": -139, "message": "Cannot unlock while initializing dynamic indexing services: Check sessions/status/local"}` error. Trying again after about 10 minutes still gives this error.

**Comment by VidereLicet** [comment]
This is an old issue related to old builds, has been resolved with new core.
