### ISSUE TITLE
To make Assets tradable on the P2P marketplace - Enhancement

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#106]
The Market API now is limited to tokens and it would be really cool to have the ability to trade assets for NXS or tokens on the marketplace

**Comment by VidereLicet** [comment]
Yeah that will be key for the geo-spacial markets. Since I'll be going into the market code to enhance it with other requested features I'll tackle this guy at the same time.

**Comment by Cybermage83** [comment]
When is geo-special markets meant to be on the road map? IT seems like 5.1 was meant for NFT marketplace, but now it not?

is this 5.2? 6.0?

**Comment by Aeonwise** [comment]
Closing this issue as there is no development happening and Nexus hitting rock bottom as Colin has takien over Nexus treasury keys and email infrastructure to control Nexus.
