### ISSUE TITLE
Names in transaction listing

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#107]
Currently the transaction list returned by ledger/list/transactions doesn't have name fields (e.g. `name_to` or `name_from`) populated. As a result, the Transactions page is pretty hard to read because only addresses are shown instead of readable names. Is it possible to make names populated in returned transactions as before?

**Comment by VidereLicet** [comment]
You want to use the profiles/transactions/master command, not ledger/list/transactions.

**Comment by VidereLicet** [comment]
Names are shown in transaction lists now under the nested format as we have discussed previously. This is from the newest commit a56ed7e21ea4b9bafb7df4bc064473ef1c0e91b2
