### ISSUE TITLE
To add the "success= true /false"in  json response for sessions/create/local, specific to Bubble.

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#109]
In Bubble when a profile local session is created, we need a condition to show that the user is logged in successfully and having the "success" value in the json response will make it easier.

In the bubble workflow image below, need to show an Alert to the user that he has logged in successfully and that alert has to show 'Only when' the condition is response of the sessions/create/local response success=true will make it easier.

<img width="341" alt="Screenshot 2023-01-27 at 11 25 27 AM" src="https://user-images.githubusercontent.com/84140911/215019262-972f00b9-6a88-41b1-8097-e5dfdd3f7d73.png">

**Comment by VidereLicet** [comment]
This issue is resolved with commit aaee003be628c4ae067d1b2d03aba7c105a3a71a
