### ISSUE TITLE
Assets/create/readonly created readonly asset without the data field.

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#110]
While creating a readonly asset, was able to create a readonly asset without providing the data field in the API call. 

This is a readonly asset created without a data field: 

["result"](http://lite4.nexenture.xyz:7080/assets/get/readonly?session=ef0b5068fde394823edda190ca9a657112caf959b23b2b73bdd2cc855c3d18fc&address=82a4eQnwYvQQ1bHETEvg717H4UC7PVdxkn3jna6zx11oJcZjhZu): {
"owner": "b76f1d57b5bc68f91d7377b7fd84073b2273c9bde6250d1ecb06e9ee4d023409",
"version": 1,
"created": 1674244804,
"modified": 1674244804,
"type": "READONLY",
"json": null,
"address": "82a4eQnwYvQQ1bHETEvg717H4UC7PVdxkn3jna6zx11oJcZjhZu",
"name": "local:Robinhood Wallet"

This is a readonly asset created with a data field:

["result"](http://lite4.nexenture.xyz:7080/assets/get/readonly?address=82dphzwfV13y9d8zFPdP9Vage6ppB8LjzEVnZHhpjUCqyEwZQbq&session=6a7abfa6fc02c79abbf414f26bb6be08ad918b7d4a4d3a97b9572738a57c6764): {
"owner": "b7fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13",
"version": 1,
"created": 1673868474,
"modified": 1673868474,
"type": "READONLY",
"data": "This is READONLY asset test data",
"address": "82dphzwfV13y9d8zFPdP9Vage6ppB8LjzEVnZHhpjUCqyEwZQbq",
"name": "local:Test Readonly"

**Comment by VidereLicet** [comment]
Fixed with commit d7f2808a963f62cb8c6cc2eb4e1dd6644c37d0b6 if you still have issues, please let me know. It looks like bubble sends null values rather than empty strings when submitting empty parameters. This should fix it, but I did not test it directly with bubble.
