### ISSUE TITLE
profiles/notifications not able to differentiate an OP:transfer for Names(name or namespace) or assets & OP:debit for token, account or trust.

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#111]
By looking at the notifications, we can differentiate between a 'debit' and a 'transfer', but not able to differentiate between an Asset or Name 'transfer' as to claim we have to use the related API calls, also Name has 'name' and 'namespace' nouns. 

Debit maybe a token, account or trust, this can be easily remedied using the any noun, but some use-cases might require more granular control on manual credit especially for De-fi. 

Looking at the notifications it is not possible to determine which API call to use, when the use-case needs to claim transactions manually.

Given below are three notifications one OP:  is debit and the other two are transfers, but one is an Asset and the other is Name transfer.

{
"id": 0,
"OP": "TRANSFER",
"address": "88LRWg4spMHeAZBjKRpj5qzmQdW4V55kM4WffZgMLLPZqRiJ7BW",
"recipient": "b76f1d57b5bc68f91d7377b7fd84073b2273c9bde6250d1ecb06e9ee4d023409",
"conditions": "(caller.genesis != 0xb7fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13 AND contract.timestamp + 604800 > ledger.timestamp) OR (caller.genesis == 0xb7fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13 AND contract.timestamp + 604800 < caller.timestamp)",
"timestamp": 1674801837,
"txid": "01da3e0c172b661dc9e7c322badff7133aae53867b2246c9683579c7a0c38e3d47659a9baf6e25437913c205552ce7d5f92ab9384741471ba7e89b47dfd34fdd"
},
{
"id": 0,
"OP": "DEBIT",
"from": "8CVAy7XaE8gonomScGy5KZsgc1k2fU1z3CZRZxqHnQRL8AGi2vX",
"to": "8BGGqkowhNcxfTJv2PEh9C61fhTHJz7JRwHUP8HMF4QgjvpzhMG",
"amount": 3,
"token": "8EMhZ9oRnJWyr7LDtfA8Sddjn4syZYPU3hFoT3ffLuc74uoiifR",
"ticker": "Apple",
"claimed": 0,
"reference": 0,
"conditions": "(caller.genesis != 0xb7fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13 AND contract.timestamp + 604800 > ledger.timestamp) OR (caller.genesis == 0xb7fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13 AND contract.timestamp + 604800 < caller.timestamp)",
"timestamp": 1674802203,
"txid": "018ec99354b3b8b1a9ca060c0b2f75db66d6ec92c9c2bc3e1aa2bffe1485ab868aaecbb78e8a31b49651f3d28af8946607bdad80c536ab70b0871ae92489c226"
},
{
"id": 0,
"OP": "TRANSFER",
"address": "8HYPYbnCp4o5iETxqHnhg8RsvSQygGPad9hxHwXGNjjBKSAUSGV",
"recipient": "b76f1d57b5bc68f91d7377b7fd84073b2273c9bde6250d1ecb06e9ee4d023409",
"conditions": "(caller.genesis != 0xb7fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13 AND contract.timestamp + 604800 > ledger.timestamp) OR (caller.genesis == 0xb7fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13 AND contract.timestamp + 604800 < caller.timestamp)",
"timestamp": 1674809908,
"txid": "01d2d737a72f7dc2f707cf1dbaa0761e45b98ed342d50b3cf3c1d884d3ab5621916687d43b4c7d102a5dc44bbae2c4ed1d2c570ee8ba585592c00724cfc8107b"
}

**Comment by Aeonwise** [comment]
For the above issue, we need to consider Supply API transfer notifications.

**Comment by VidereLicet** [comment]
Resolved with commit 2fe6d7be0185c01418fa45ca4a820f7a6ba89717. You can find all the relevant info for DEBIT/CREDIT inside the to and from keys, they include address, name, and type. All other contracts supply a type key so you can know what type of register that contract is operating on. Recipient inside TRANSFER now supports nested values if tokenizing an asset, it will give you the info about the token being transferred to such as address, name, and type.
