### ISSUE TITLE
Supply API: POST API calls where the item has to be searched, returns "invalid address", if only the name is provided.

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#113]
The supply API POST calls, where the node has to search for the particular item to carry out the operation like update / transfer give the error "invalid address" when searched with only the name.

Tried with name using the username:itemname format and also using only itemname, both do not work. If the address is provided then it works perfectly.

The API Call:
<img width="672" alt="Screenshot 2023-01-29 at 11 32 51 PM" src="https://user-images.githubusercontent.com/84140911/215346422-8a60d19a-826d-4f72-b237-ad6c571e53ac.png">

**This is the error message received:**
<img width="804" alt="Screenshot 2023-01-29 at 11 16 43 PM" src="https://user-images.githubusercontent.com/84140911/215346434-16d51e2b-9c81-40e2-992a-fb6a4683aa5f.png">

**Comment by VidereLicet** [comment]
This issue is resolved with commit 5c9035733293a675caeb24fbe0625e937774ca18
