### ISSUE TITLE
Invoices API -  The invoice "name" is not returned with the get/list/history verbs

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#115]
When using the invoice get/list/history API the invoice "name" is not returned.

Sample response:

{
  "result": [
    {
      "status": "TRANSFER",
      "owner": "00fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13",
      "version": 1,
      "created": 1675501231,
      "modified": 1675501231,
      "type": "READONLY",
      "form": "INVOICE",
      "json": {
        "account": "8CY5McbYXHiLgBqM54F1kXK5t7rx2hQBTEYzgioaQLMZ8LC1JxW",
        "recipient": "b76f1d57b5bc68f91d7377b7fd84073b2273c9bde6250d1ecb06e9ee4d023409",
        "items": [
          {
            "amount": 40,
            "units": 1,
            "description": "BIke Painting"
          }
        ],
        "to": "8CY5McbYXHiLgBqM54F1kXK5t7rx2hQBTEYzgioaQLMZ8LC1JxW",
        "reference": "BIke maintenance & painting",
        "description": "Enfield KA19 ES-2341",
        "number": "0001",
        "due_date": "null",
        "sender_detail": "Aeon",
        "recipient_detail": "Test User",
        "amount": 85,
        "token": "8Cx2CFaNuyUWHRbrZXFXXj4rugMA5Jqk4PtZWV9xYANt4AuNaKU",
        "status": "OUTSTANDING"
      },
      "address": "81mbYBaS4KWHpSgCeovD228Siz83o4YqAwVdF3tyQRnvHtfTxwq"
    }
  ],
  "info": {
    "method": "invoices/list",
    "status": "active",
    "address": "54.184.10.91:36994",
    "latency": "0.929922 ms"
  }
}

**Comment by VidereLicet** [comment]
This is duplicate issue to the missing 'name' record for RAW and READONLY, closing.
