### ISSUE TITLE
Invoices API - The invoice amount calculated is not accurate.

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#116]
When creating new invoice found:
1.  when decimals are used in the "items - amount" field, the amount in the created invoice json response is completely different.
2. when creating the invoice the "items - units" should be a supplied as a string with "" or else it reports an error. Not sure if this is the correct? but it has not created errors when using integers (whole numbers) in the "amount" field

**Sample Json body used to create the invoice:**

{   
    "name": "Test Invoice",
	"to": "8BN2Lj35PTYwuRyoKHxVY1iySbQywrQ6DayMGm499sF5p1NEhXH",
    "recipient": "Test",
    "reference": "Software Services",
    "description": "Application Development",
    "number": "001",
	"sender_detail": "Aeon",
    "recipient_detail": "Test",
    "session": "376685adcaa70c7feef1002f8874ecf095e00f294795bd85f98e60c56bed2fd8",
	"pin": 1234,
  	"items": [
          {
              "description": "Prototyping",
              "units": "1",
              "amount": 50.5
          },
		  {
              "description": "MVP",
              "units": "1.25",
              "amount": 70.5
          },
          {
              "description": "Consultation",
              "units": "2.35",
              "amount": 20
          }
      ]
      
}

**The created invoice return json:**

{
            "status": "TRANSFER",
            "owner": "00fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13",
            "version": 1,
            "created": 1675499873,
            "modified": 1675499873,
            "type": "READONLY",
            "form": "INVOICE",
            "json": {
                "account": "8BN2Lj35PTYwuRyoKHxVY1iySbQywrQ6DayMGm499sF5p1NEhXH",
                "recipient": "b76f1d57b5bc68f91d7377b7fd84073b2273c9bde6250d1ecb06e9ee4d023409",
                "items": [
                    {
                        "amount": 0.00005,
                        "units": 1,
                        "description": "Prototyping"
                    },
                    {
                        "amount": 0.00007,
                        "units": 1,
                        "description": "MVP"
                    },
                    {
                        "amount": 0.00012,
                        "units": 2,
                        "description": "Consultation"
                    }
                ],
                "to": "8BN2Lj35PTYwuRyoKHxVY1iySbQywrQ6DayMGm499sF5p1NEhXH",
                "reference": "Software Services",
                "description": "Application Development",
                "number": "001",
                "sender_detail": "Aeon",
                "recipient_detail": "Test",
                "amount": 0.00036,
                "token": "8Eo2aGS6BZGbATNQiUCWaFTgmvq3GuDibxB8HRJKKePGY4U3RYD",
                "status": "OUTSTANDING"
            },
            "address": "82HVt17qPEqSKqRSTzrwhUVqUnVeoZafAgit42SEwZyximnTRmJ"
        }
    ],
    "info": {
        "method": "invoices/list",
        "status": "active",
        "address": "117.248.87.141:27773",
        "latency": "0.891335 ms"
    }
}

**Comment by VidereLicet** [comment]
Fixed with commit 5fd0a95515ecd9b9e6d6e4c3450050a9ea1df83b
