### ISSUE TITLE
Profiles API is showing duplicate notifications & the 'type' for the NXS default account is labeled as 'TRUST'

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#117]
On the test-net with the latest merging build found duplicate notifications for a debit and also the 'type' descriptor for the default account is showing as 'TRUST' instead of "ACCOUNT'

This is the notification result for a single debit transaction and you can see that we have a duplicate entry with the same details:
    
{
    "result": [
        {
            "id": 0,
            "OP": "DEBIT",
            "from": {
                "address": "8GexHBPmQBv4gAV6qykGaiZhUZbHC6kAFMkjSfCmXGVKQ5V6LCB",
                "name": "local:trust",
                "type": "TRUST"
            },
            "to": {
                "address": "8CfkChcB37aXDTnUcnEzBwmmguyzLu3p2FrGju73tM8ceqsU4Po",
                "name": "local:default",
                "type": "TRUST"
            },
            "amount": 2,
            "token": "0",
            "ticker": "NXS",
            "claimed": 0,
            "reference": 0,
            "timestamp": 1676128555,
            "txid": "0125222865bba8c1d847c87664ffc32b9040b338359ef879ceeb5be08ab03c70b84d92d5cd6f9286322e5a05d764f01034cdc2e028e873098bb1747553849a13"
        },
        {
            "id": 0,
            "OP": "DEBIT",
            "from": {
                "address": "8GexHBPmQBv4gAV6qykGaiZhUZbHC6kAFMkjSfCmXGVKQ5V6LCB",
                "name": "local:trust",
                "type": "TRUST"
            },
            "to": {
                "address": "8CfkChcB37aXDTnUcnEzBwmmguyzLu3p2FrGju73tM8ceqsU4Po",
                "name": "local:default",
                "type": "TRUST"
            },
            "amount": 2,
            "token": "0",
            "ticker": "NXS",
            "claimed": 0,
            "reference": 0,
            "timestamp": 1676128555,
            "txid": "0125222865bba8c1d847c87664ffc32b9040b338359ef879ceeb5be08ab03c70b84d92d5cd6f9286322e5a05d764f01034cdc2e028e873098bb1747553849a13"
        }
    ],
    "info": {
        "method": "profiles/notifications",
        "status": "active",
        "address": "117.192.180.201:58936",
        "latency": "0.292961 ms"
    }
}

**Comment by VidereLicet** [comment]
This is fixed with commit b6b2b5ae377139a13eb61fa139d70e32611a6766 and also commit 685dbadbc9e83bdce5e45a16a23b154a348f2c56. It was using the contract's pre-state to generate the standards data for 'to' keys when that should have done a register lookup instead.
