### ISSUE TITLE
Sessions API - Load/local needs a 'Success' flag

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#119]
The sessions/load/local results needs a 'success' =true/false  flag which will be required by use-case developers.

**The output for sessions/load/local :**

  "body": {
    "result": {
      "genesis": "b7fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13",
      "session": "95c78d79213c454be14a734d15cf9ad46f67c617ff405845fad22c6ad66110a8"
    },
    "info": {
      "method": "sessions/load",
      "status": "active",
      "address": "54.218.98.164:41734",
      "latency": "1.249632 ms"
    }

**Comment by VidereLicet** [comment]
Any reason you can't check the error message instead? It will return an error key with the error code if login failed
