### ISSUE TITLE
Private node crash 

### ISSUE THREAD

**Issue by Brad241** [Nexusoft/LLL-TAO#120]
Uncommon, but encountered issue with a private node whereby the node is still live, but won't receive any API requests. Once the node is restarted all issues are resolved, however unless restarted the issue persists. When reviewing the logs it is not clear what the cause of the issue is. The logs show a number of API requests from unauthorised IP addresses that are blocked by the system.

**Comment by VidereLicet** [comment]
We are tracking this deadlock now, thank you for the report!
