### ISSUE TITLE
Fails to Compile --- 

### ISSUE THREAD

**Issue by Gapcoin1** [Nexusoft/LLL-TAO#125]
src/LLC/eckey.cpp: In function ‘int LLC::ECDSA_SIG_recover_key_GFp(EC_KEY*, BIGNUM*, BIGNUM*, const unsigned char*, int, int, int)’:
src/LLC/eckey.cpp:203:13: error: could not convert ‘BN_zero_ex(zero)’ from ‘void’ to ‘bool’
  203 |         if(!BN_zero(zero))
      |             ^~~~~~~
      |             |
      |             void
src/LLC/eckey.cpp:203:13: error: in argument to unary !

**Comment by VidereLicet** [comment]
What's your openssl version? Should be using 1.1 sudo apt-get install libssl1.1-dev
