### ISSUE TITLE
Change Prime Channel Mining to Signed-POW to Require running a Tritium GUI Node with Built in miner

### ISSUE THREAD

**Issue by Github-420** [Nexusoft/LLL-TAO#126]
Change Prime Channel Mining to Signed-POW to Require running a Tritium GUI Node with Built in miner and Signing all generated Block Headers with a Signing Key from the Tritium Account Miner

LLL-TAO Part of this NexusInterface Issue
 
https://github.com/Nexusoft/NexusInterface/issues/198

**Comment by Github-420** [comment]
This is needed to Decentralize and SIMPLIFY the mining! 

IDK about the GPU mining channel

**Comment by NamecoinGithub** [comment]
https://github.com/Karbovanets/papers/blob/master/SPOW.md

After reading the SPOW White Paper it seems maybe this is specific to the Cryptonote Architecture, but the logic could probably still be adapted to other Architectures

I like idea of Decentralizing the Mining away from Pools, and even if it's not CPU built in Miner with Tritium, having GPU mining if possible to use GUI Tritium Built in Miner with possible staking would be ideal for long term Centralization attacks

SPOW is designed against Pools not to only allow CPU mining YesPower seems to be for CPU mining which KARBO adopted at the same time as SPOW

But if Nexus reverted back to it's original roots wanting a GPU AND CPU mining Channels a purpose made CPU algo would have to be incorporated to replace 1 of the existing Channels

But than you would be facing the design feature if you want to allow 1 Channel to still be dominated by a few Pools, or weather to alter Both Channels to SPOW and make the Tritium GUI Built-In Miner handle both GPU and CPU mining as well as Possibly Staking at the same time WITHOUT Pools

But to be honest I have studied some of the large GPU miners they are very impressive, I am unsure how well that would work out for them, but for CPU I know it's a perfect fit to have a CPU Desktop be able to Mine Nexus and earn some NXS, of course it's probably not appealing enough to get 25-100 Different Individual CPU Nodes running as the Cryptocurrency Desktop miners is very very low appeal, but for Decentralization it's a critical requirement long-term to combat Centralization Attacks

**Comment by NamecoinGithub** [comment]
Longer-Term I love the idea because I would much rather have a Simplified Tritium Wallet if I didn't want to use any other features other than mining staking and some other basic functions! 

But of course all you would have to do is close that Tritium wallet and Open the other Wallet with the Marketplace ect...........and whatever other Modules you might have installed

**Comment by VidereLicet** [comment]
Currently every block is signed with the proof of work, but we are not going to fight the GPU usage as CPU only just get ravaged by botnets. The prime channel does already combat centralization, to eliminate pools we are developing the multi dimensional chaining model.
