### ISSUE TITLE
Dockerfile uses latest debian stable which is version 10 but libssl1.0-dev is incorrect

### ISSUE THREAD

**Issue by andre-brongniart** [Nexusoft/LLL-TAO#13]
apt should be installing libssl-dev not libssl1.0-dev.

**Comment by andre-brongniart** [comment]
You can use 'debian:9' for the image...

**Comment by VidereLicet** [comment]
Replaced with LISP specific dockerfile: https://github.com/Nexusoft/LLL-TAO/commit/7e9027f504f4c10c924b4ffb188520b175233063
