### ISSUE TITLE
Previous Transactions and Accounts page is blank 

### ISSUE THREAD

**Issue by rayanfer32** [Nexusoft/LLL-TAO#137]
```
wallet_version: 3.1.0 on Lite mode
system: Windows 8.1
Wallet version
3.1.0
Wallet build date
April 26th 2023
Nexus Core version
5.1.0 Tritium++ CLI [LLD][x64]
Core build date
April 26th 2023
```
![image](https://github.com/Nexusoft/LLL-TAO/assets/37145078/d2e2a9d0-93e6-44fd-8001-0092f378e656)

![image](https://github.com/Nexusoft/LLL-TAO/assets/37145078/0e335eba-bea5-480c-ae59-a2f67295dde6)

![image](https://github.com/Nexusoft/LLL-TAO/assets/37145078/998ad16c-1b45-4d5c-81c5-1b94c9451ce2)

![image](https://github.com/Nexusoft/LLL-TAO/assets/37145078/dc16db82-7c90-4b40-abe4-ebac160b49c3)

![image](https://github.com/Nexusoft/LLL-TAO/assets/37145078/aa1ff317-cb10-4ebb-ad32-a2e6401ad58d)

**Comment by VidereLicet** [comment]
I found some backend issues on my nodes, is this still a problem? Kendal also made a fox for transactions history page
