### ISSUE TITLE
Market API - market/list/ does not list active bids/asks/orders

### ISSUE THREAD

**Issue by AkstonCap** [Nexusoft/LLL-TAO#139]
![bilde](https://github.com/Nexusoft/LLL-TAO/assets/88211167/d66b5b86-5b61-4d9c-97c6-0070b49bfdea)
Creating and cancelling bids seem to work fine, but running market/list/bid only gives an empty output.
See attached screenshot from wallet API (5.1.0).

**Comment by VidereLicet** [comment]
Looking into this now, will report back when fixed

**Comment by VidereLicet** [comment]
Fixed with commit https://github.com/Nexusoft/LLL-TAO/commit/587ac9b11cb4b0d2da63c2697c7b59f3fbf98489
