### ISSUE TITLE
openssl compile error

### ISSUE THREAD

**Issue by kr1z1s** [Nexusoft/LLL-TAO#140]
I use openssl version - openssl-1.1.0l - https://www.openssl.org/source/old/1.1.0/openssl-1.1.0l.tar.gz

But i have this error

`Compiling build/main.o
build/LLC_eckey.o: In function `LLC::ECKey::SetCompactSignature(base_uint<256u>, std::vector<unsigned char, std::allocator<unsigned char> > const&)':
eckey.cpp:(.text+0x120f): undefined reference to `ECDSA_SIG_set0'
build/LLC_eckey.o: In function `LLC::ECKey::SignCompact(base_uint<256u>, std::vector<unsigned char, std::allocator<unsigned char> >&)':
eckey.cpp:(.text+0x19b4): undefined reference to `ECDSA_SIG_get0'
build/LLC_bignum.o: In function `LLC::CBigNum::getint32() const':
bignum.cpp:(.text+0x2199): undefined reference to `BN_is_negative'
build/LLC_bignum.o: In function `LLC::CBigNum::operator!() const':
bignum.cpp:(.text+0x3908): undefined reference to `BN_is_zero'
build/LLC_bignum.o: In function `LLC::operator-(LLC::CBigNum const&)':
bignum.cpp:(.text+0x582d): undefined reference to `BN_is_negative'
build/LLC_bignum.o: In function `LLC::CBigNum::ToString[abi:cxx11](unsigned int) const':
bignum.cpp:(.text+0x68d9): undefined reference to `BN_is_negative'
build/LLP_socket.o: In function `LLP::Socket::Socket(LLP::Socket const&)':
socket.cpp:(.text+0x40a): undefined reference to `SSL_up_ref'
build/LLP_socket.o: In function `LLP::Socket::Close()':
socket.cpp:(.text+0x5eb): undefined reference to `SSL_is_init_finished'
build/LLP_socket.o: In function `LLP::Socket::IsSSL() const':
socket.cpp:(.text+0xbee): undefined reference to `SSL_is_init_finished'
build/LLP_socket.o: In function `LLP::Socket::Socket(int, LLP::BaseAddress const&, bool const&)':
socket.cpp:(.text+0x1b7e): undefined reference to `SSL_is_init_finished'
build/LLC_x509_cert.o: In function `LLC::X509Cert::GenerateRSA(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)':
x509_cert.cpp:(.text+0x1197): undefined reference to `X509_set1_notBefore'
x509_cert.cpp:(.text+0x11b0): undefined reference to `X509_set1_notAfter'
build/LLC_x509_cert.o: In function `LLC::X509Cert::GenerateEC(base_uint<512u> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)':
x509_cert.cpp:(.text+0x30b8): undefined reference to `X509_set1_notBefore'
x509_cert.cpp:(.text+0x30d2): undefined reference to `X509_set1_notAfter'
build/LLC_x509_cert.o: In function `LLC::X509Cert::Hash()':
x509_cert.cpp:(.text+0x356c): undefined reference to `X509_get_version'
x509_cert.cpp:(.text+0x3656): undefined reference to `X509_getm_notBefore'
x509_cert.cpp:(.text+0x36a6): undefined reference to `X509_getm_notAfter'
build/LLP_network.o: In function `LLP::NetworkInitialize()':
network.cpp:(.text+0x167): undefined reference to `OPENSSL_init_ssl'
network.cpp:(.text+0x170): undefined reference to `OPENSSL_init_ssl'
network.cpp:(.text+0x175): undefined reference to `TLS_method'
network.cpp:(.text+0x1bc): undefined reference to `SSL_CTX_set_options'
build/Legacy_crypter.o: In function `Legacy::EncryptSecret(std::vector<unsigned char, secure_allocator<unsigned char> > const&, std::vector<unsigned char, secure_allocator<unsigned char> > const&, base_uint<576u> const&, std::vector<unsigned char, std::allocator<unsigned char> >&)':
crypter.cpp:(.text+0x8c4): undefined reference to `EVP_CIPHER_CTX_reset'
build/Legacy_crypter.o: In function `Legacy::Crypter::Encrypt(std::vector<unsigned char, secure_allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&)':
crypter.cpp:(.text+0xb3d): undefined reference to `EVP_CIPHER_CTX_reset'
build/Legacy_crypter.o: In function `Legacy::Crypter::Decrypt(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, secure_allocator<unsigned char> >&) [clone .part.61]':
crypter.cpp:(.text+0xd26): undefined reference to `EVP_CIPHER_CTX_reset'
collect2: error: ld returned 1 exit status`

Which version should I use?

**Comment by VidereLicet** [comment]
Need to use correct version @1.1.1 I believe, these issues are usually related to versions
