### ISSUE TITLE
Private Network - Account balances not updating following debit from token address

### ISSUE THREAD

**Issue by Brad241** [Nexusoft/LLL-TAO#141]
Using the testnode. Prior to the test, I updated the node to the latest commit. (https://github.com/Nexusoft/LLL-TAO/commit/f6ac9f4414c1428d4007cde0048a448990088be2)

**Actions:**
1. Created a token - success (get/transaction result screenshot below)
![image](https://github.com/Nexusoft/LLL-TAO/assets/85960958/786444ff-cec5-4d44-adc6-c1e86f9c3ba0)

2. Created a token account - success
![image](https://github.com/Nexusoft/LLL-TAO/assets/85960958/df53a6c6-7423-4ef5-9761-6ac40228bacf)

3. Debited the full token balance to the sig chain's token account (when I run finance/get/token the balance is shown as 0)
![image](https://github.com/Nexusoft/LLL-TAO/assets/85960958/cc98c2b4-93d3-4a98-bfc0-c977b917f2bf)

**Issue:**
When using finance/get/account or register/list/finance:accounts, the token account balance is 0 when it should be 20,000. I can confirm the correct token account was debited to, so it was not a user error. (see 2nd screenshot below)

![image](https://github.com/Nexusoft/LLL-TAO/assets/85960958/28841636-55ab-4805-ba66-b7ea02fe9df0)
![image](https://github.com/Nexusoft/LLL-TAO/assets/85960958/c283000b-f675-45b6-92b9-b1f5406d9b1c)

**Comment by Brad241** [comment]
FYI in case the node is reviewed. I have reverted node back 33 commits from current commit (see above) to a time when the issues did you occur.

**Comment by VidereLicet** [comment]
Never seen debits fail, are you sure it was logged in? You need to give me circumstances I can replicate otherwise it's just guessing

**Comment by Brad241** [comment]
After testing on two separate testnodes (I have a separate node for demos + the Nexus general testnode) whether I run profiles/notifications/master or sessions/unlock/local, both **do not** result in the credits being claimed. In all cases, the creator of the token was logged in at the time of the debit and was unlocked for notifications.

The tokens are successfully created, the accounts are created successfully, it appears that the transactions are completed, but the receiving account does not claim the tokens. This has only been tested with Tokens and not Assets. This has been replicated across a number of accounts and sig chains, so doesn't appear to be an isolated event.

Attached are the logs for the demo testnet. I have highlighted the POST profiles/notifications/master. There were no errors shown in the logs, however the debits were never claimed by the intended recipient account.

[Evidence logs 1.pdf](https://github.com/Nexusoft/LLL-TAO/files/11681662/Evidence.logs.1.pdf)

**Comment by VidereLicet** [comment]
Was a simple issue, testnode has no connections since it's single node. Events weren't processing without, fixed with commit https://github.com/Nexusoft/LLL-TAO/commit/441807018dec9cf58b6c3cb810c834067bf0d44b
