### ISSUE TITLE
Richlist API cannot distinguish Legacy accounts

### ISSUE THREAD

**Issue by MerlinSpectre** [Nexusoft/LLL-TAO#150]
Currently Richlist API cannot provide an accurate Address for Legacy Accounts. 
![Legacy Accounts](https://github.com/Nexusoft/LLL-TAO/assets/17627993/753e8f9b-ad22-4e43-8710-6909bbf2cd14)

**Comment by VidereLicet** [comment]
This has since been resolved with -indexaddress
