### ISSUE TITLE
Recover account when password / pin forgotten

### ISSUE THREAD

**Issue by Brad241** [Nexusoft/LLL-TAO#154]
Private node running on the latest merging commit (fb70bf65818e82aa6d966681c2d03ea0800b76a0)

This issue was experienced when recovering accounts that have forgotten their password or pin. 

Note: I tested the resetting of passwords / pins / recovery phrases when the user is logged in and it worked fine – this only appears to happen when the user is not logged in and hasn’t accessed their account in a while. I've tested with a few accounts: one hadn’t been accessed in 3 months and the other had logged in (and logged out) a few minutes before I ran the test. 

The issue only occurred when the user had not logged in for a while.  When the recovery phrase is used to reset the password / pin the following error message was received:

Raw error: {&quot;error&quot;:{&quot;code&quot;:-32,&quot;message&quot;:&quot;Failed to accept. \u001b[1mAccept\u001b[0m : 
CONFLICT: hash last mismatch 01472dda01786820a7c9 and 014b61995eaae0b87f52&quot;},&quot;info&quot;:{&quot;method&quot;:&quot;profiles/recover&quot;,&quot;status&quot;:&quot;active&quot;,&quot;address&quot;:&quot;35.86.123.106:39098&quot;,&quot;latency&quot;:&quot;3901.299293 ms&quot;}}

**Comment by Brad241** [comment]
Another issue found with the latest commit is related to creating a token account shortly after creating a new profile - the following error message is received:

Nexus - Finance API: create/account just returned an error (HTTP 400). Please contact the plugin author directly for feedback. Raw error: {&quot;error&quot;:{&quot;code&quot;:-32,&quot;message&quot;:&quot;Failed to accept. \u001b[1mAccept\u001b[0m : CONFLICT: prev tx CLAIMED 0169b262716124884a23&quot;},&quot;info&quot;:{&quot;method&quot;:&quot;finance/create&quot;,&quot;status&quot;:&quot;active&quot;,&quot;address&quot;:&quot;34.222.212.227:57888&quot;,&quot;latency&quot;:&quot;1260.553221 ms&quot;}}

**Comment by VidereLicet** [comment]
Fixed with commit fa4213396f4dbe52402b8f3eec57d74cb2890d4f
