### ISSUE TITLE
Bittrex is Down Dec 4, 2023 Another SBF/FTX Casualty!!!!!!  NXS needs a 2nd Exchange listing!

### ISSUE THREAD

**Issue by NamecoinGithub** [Nexusoft/LLL-TAO#156]
SOUTHxCHANGE is closing down!

https://miningpoolstats.stream/nexus

Haveno Exchange is in Beta, this would be perfect to Integrate Monero instead of maybe Bitcoin Blockchain into the Old Nexus Blockchain ect..........

![Skærmbillede på 2024-01-17 12-22-11](https://github.com/Nexusoft/LLL-TAO/assets/130555019/36c03ad7-334f-44f6-af1e-7b8ea7cb4155)
![Skærmbillede på 2024-01-17 12-23-25](https://github.com/Nexusoft/LLL-TAO/assets/130555019/50f75da8-c461-4ed8-8918-bb8a6aa1c28d)

![Skærmbillede på 2024-01-17 12-25-14](https://github.com/Nexusoft/LLL-TAO/assets/130555019/91d16dd3-50ca-45bb-8a29-bea5c259efd4)
![Skærmbillede på 2024-01-17 12-25-46](https://github.com/Nexusoft/LLL-TAO/assets/130555019/59fe7f13-ab50-4dfa-8882-0a96399f2b3f)
![Skærmbillede på 2024-01-17 13-47-01](https://github.com/Nexusoft/LLL-TAO/assets/130555019/161be75b-dfa6-4108-9bbe-7feffdf195ca)

**Comment by NamecoinGithub** [comment]
I signed up to nonkyc.io it's simple and easy enough and allows longer passwords than Tradeogre..........however it requires phone app 2-factor which ties phone GPS to Physical Withdraw Addresses which poses risks to Physical Safety if the data is ever leaked or hacked with the GPS from the Phone!  But it's maybe ok to most people, still way better than most other choices available, the Exchange seems well done almost like using Binance Clone!


The Monero Exchange is coming, it's still being worked on apparently after the main developer of it left last year and it's still getting a lot of Code Done to make it happen!

https://github.com/haveno-dex

https://haveno.exchange/

This would be another good option coming up, but yet I have no idea how it will work out from this perspective until it's actually released as Official Launch of the Haveno Exchange!

**Comment by NamecoinGithub** [comment]
https://github.com/Nexusoft/LLL-TAO/issues/133#issuecomment-1581959108

I think it would be better to Integrate with Haveno and use a Different Application for the Exchange would be fastest way to integrate with NXS!  And it wouldn't require a NXS Module installed to operate the Exchange!

Videlicet
> That's what I was thinking yeah, and our legacy code is based on Bitcoin so we could modify it to support connections to Bitcoin network too. This is an awesome feature

**Comment by VidereLicet** [comment]
Thanks mate, we will take a look at these!
