### ISSUE TITLE
Error compiling - Ubuntu

### ISSUE THREAD

**Issue by AmDDJunkie** [Nexusoft/LLL-TAO#157]
Following instructions on this github,
Ran command "make -j 4 -f makefile.cli"
Received the below error:
Compiling src/LLC/hash/SK/skein.cpp
Compiling src/LLC/hash/SK/skein_block.cpp
In file included from /usr/include/openssl/asn1.h:33,
                 from /usr/include/openssl/ec.h:92,
                 from /usr/include/openssl/ecdsa.h:10,
                 from src/LLC/eckey.cpp:16:
src/LLC/eckey.cpp: In function ‘int LLC::ECDSA_SIG_recover_key_GFp(EC_KEY*, BIGNUM*, BIGNUM*, const unsigned char*, int, int, int)’:
src/LLC/eckey.cpp:203:13: error: could not convert ‘BN_zero_ex(zero)’ from ‘void’ to ‘bool’
  203 |         if(!BN_zero(zero))
         |             ^~~~~
         |             |
         |             void
src/LLC/eckey.cpp:203:13: error: in argument to unary !
Compiling src/LLC/hash/SHA3/sha3.c
make: *** [makefile.cli:1237: build/LLC_eckey.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by AmDDJunkie** [comment]
Issue #125 states to use openssl 1.1 to resolve this error, however thats end of life. Is that still required for Nexus?

**Comment by NamecoinGithub** [comment]
A lot of people have reported this issue since couple months ago, and no one knows about the real cause!

Colin has removed the OpenSSL dependency last week but it's not yet Merged into Merging Branch its in Merging-LLC branch if you know how to merge it yourself to try!  I have not tried it yet!

https://github.com/Nexusoft/LLL-TAO/commit/b5f0e31c4b1a3ea0ebbfebbf162b41b998d8e4b5

https://github.com/Nexusoft/LLL-TAO/commit/79258ccdd5115a30fdc66929188f330304d7467f

https://github.com/Nexusoft/LLL-TAO/commit/95c2639e1c720172a4fbab6df0968b06ea957bd2

**Comment by AmDDJunkie** [comment]
Appreciate the info, I have no idea how to merge myself so I'll have to wait.
Thank you

**Comment by ThomasRScott** [comment]
To compile 5.1.1-rc17.2 On Ubuntu 22.04 Do the following in src/LLC/eckey.cpp

Comment out lines 203 - 207

203         /*if(!BN_zero(zero))
204         {
205             ret=-1;
206             goto err;
207         }*/

Add a new line at 209

208 
209         BN_zero(zero);
210         

Modified source is now:

203         /*if(!BN_zero(zero))
204         {
205             ret=-1;
206             goto err;
207         }*/
208 
209         BN_zero(zero);
210         
211         if(!BN_mod_sub(e, zero, e, order, ctx))
212         {   
213             ret=-1;
214             goto err;
215         }
216         

compile....

**Comment by NamecoinGithub** [comment]
> To compile 5.1.1-rc17.2 On Ubuntu 22.04 Do the following in src/LLC/eckey.cpp
> 
> Comment out lines 203 - 207
> 
> 203 /* if(!BN_zero(zero)) 204 { 205 ret=-1; 206 goto err; 207 } */
> 
> Add a new line at 209
> 
> 208 209 BN_zero(zero); 210
> 
> Modified source is now:
> 
> 203 /*if(!BN_zero(zero)) 204 { 205 ret=-1; 206 goto err; 207 }*/ 208 209 BN_zero(zero); 210 211 if(!BN_mod_sub(e, zero, e, order, ctx)) 212 { 213 ret=-1; 214 goto err; 215 } 216
> 
> compile....

Umm...........Thanks Do you want me to Create a Pull Request for you as I see your profile is private..........I checked it out after a few tries with your Code and got it to Compile..........THANKS

It helped me Isolate that the Hard Fork Occurring in the New Release is NOT coming from the Interface, but the LLL-TAO code, as I wasn't able to test the LLL-TAO code until using your code to compile it!

It was a little tricky and I had to keep at it to get the trick right from you, I know how to make things easy so it didn't take me long at all!

https://github.com/Nexusoft/NexusInterface/issues/226

**Comment by ThomasRScott** [comment]
NamecoinGithub - Glad you got it working ...

**Comment by VidereLicet** [comment]
This has been merged, thanks @NamecoinGithub
