### ISSUE TITLE
Blockchain Sync Fails Everytime @ same Block 342,615

### ISSUE THREAD

**Issue by NamecoinGithub** [Nexusoft/LLL-TAO#159]
Hi,

I just saw you put out a New LLL-Tao version release, I compiled it and compiled the most recent UPnP patch but it still Hard Forks using Source Code Node

Reference to New Interface Wallet issue

https://github.com/Nexusoft/NexusInterface/issues/226

**Comment by VidereLicet** [comment]
What node are you connecting to? Can you get me an IP so I can write some safeguards? Great quote by the way :)

**Comment by VidereLicet** [comment]
Just specific nodes to play around with, when you scroll up in your logs, do you see any error messages? Unsoliced notification means someone is sending you notifications but you didn't subscribe to them. The ORPHAN chains I see above don't necessarily look like forks unless there is an error message above them. Sometimes a node will deliver a set of blocks that's +1 block from your best height and so they will all be registered as oprhans. Then the Tritium Protocol will check if you have too many consecutive orphans and switch to another node if this ever happens. A hard fork will be indicated by a failed checkpoint or some error message in Accept or Index. Let me know if you can get me some more logs to I can verify this for sure.

**Comment by NamecoinGithub** [comment]
Well, it's like a Hard Fork because it's always @ the Same Block Height!

I deleted the .nexus folder and tried resync with current LLL-Tao, it's just more of the same really, once it gets to that Block it just starts its DDOS Attack spamming Orphan from off that Block Height!

The only difference is the first time I started Nexus the Orphan Block got thrown right away, and my Bandwidth was very low however when I check .nexus folder it said 900 mb, it didn't start registering checkpoints until I restarted Nexus!

If you want to check Nodes I would start with these!
![Skærmbillede på 2024-02-21 21-10-10](https://github.com/Nexusoft/LLL-TAO/assets/130555019/0cefa02d-2025-45c2-b4dd-1a1ce2cffe83)
![Skærmbillede på 2024-02-21 21-10-33](https://github.com/Nexusoft/LLL-TAO/assets/130555019/f109f89f-5dcf-44c8-8d83-4cbddd9c1657)
![Skærmbillede på 2024-02-21 21-11-28](https://github.com/Nexusoft/LLL-TAO/assets/130555019/f82cf994-f7a8-42b1-94b2-a1187e2b3fa7)


104.192.170.130
66.85.76.106
69.195.146.126


It's a problem not to be able to Sync, and I don't want to Sync without a VPN, as I don't trust these other Nodes :)

**Comment by NamecoinGithub** [comment]
Using New 3.1.3 Nexus Interface I got to the same Block 342,615 with same result, I had to restart the Wallet for it to get past Block 2999

Using Compiled LLL-Tao

A little different this Time using LLL-Tao that I need to update with new Photos!

This New Update Details the Socket Proxy of different Nodes!

5.188.104.245  (Russia)  into (77.109.112.223 Belgium) into (85.221.152.47 Poland)


104.192.169.62  (US) into   193.56.105.217 (Poland)


159.69.219.21 (Germany)  into 46.166.29.38 (Moldova)


Is there a nexus.conf Command to Block Nodes that I can play with?

Thanks

**Comment by NamecoinGithub** [comment]
![Skærmbillede på 2024-05-19 14-24-13](https://github.com/Nexusoft/LLL-TAO/assets/130555019/b0311d9a-0312-4e80-baed-e8f3a03b59ab)

Since the CHI-COM pool shut down, the Sync is Clean everytime but still throws the Orphan @ same Block!  There is No Yellow Messages, it was all clean first time!  But still threw the Orphan!

**Comment by NamecoinGithub** [comment]
Request to Hard Fork block # 342,615 unless a fix is provided another way!  

If I will be able to Sync the Blockchain I will pay the 100 Nexus to cover it, but that will require a different coded Block inside the Hard Fork Block to Pay it All! 

![Skærmbillede på 2024-07-19 00-47-56](https://github.com/user-attachments/assets/96b0f6d7-dd85-4b1a-9259-c3896b0519a8)

39.447346
2SQB4wWgbd4hMcJrjJ4EapP3xGvvYaG2pSKRXTqe9fEA7hTgMa7

11.022069
2RwtQdi3VPPQqht15QmXnS4KELgxrfaH2hXSywtJrfDdCJMnwPQ

0.999864
2RURDVPFD14eYCC7brgio2HF77LP22SdN5CeAvwQAwdSPdS95dT

And 51.469279 for the Block Creation, but IDK how to Zero out the Amount from this Block it's been Transferred, it will work in reality using Offsets inside the Hard Fork Block, I really want to be able to Sync past this Block!  But if it's some other Code issue since the last 2 updates IDK!  

I would like to be able to Stake my Coins ect............so I am actually a lot more @ a Loss than this in Reality!  My Loss is in the Thousands from not being able to Stake!  

Thanks

**Comment by VidereLicet** [comment]
Have you tried this using the newest release 5.1.4?

**Comment by NamecoinGithub** [comment]
IDK, if this update fixed the issue or not!

The Connections are much improved! I no longer lose most of my connections over time or after changing VPN Locations as before this update, which is Awesome BTW!

However, I did compile the newest Nexus Tao but it still failed at this Block, trying to Sync from Scratch! But I will try again soon more!

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by VidereLicet** [comment]
Perfect thanks for the info, I'll do a sync from scratch and see if I can replicate and fix this for the next wallet release.

**Comment by VidereLicet** [comment]
I was able to replicate the issue, tracing to where it's coming from now. You can compile for Linux right? Would like to get you to test it out once I push the fix to merging

**Comment by NamecoinGithub** [comment]
I can do that, I read most of your Code now anyway, and only Compile when I think it's interesting to try fixes!

I will report here and Close this After I test it! (If everything works good), seems like the Connections issue you fixed was just as big of issue for me too, which seems fixed now first time, I can remember!

I am just glad you got it to Replicate!

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by VidereLicet** [comment]
I finally tracked this one down, go ahead and compile it and you'll sync from scratch with no issues. Commit that resolved it is 63e240ce2c5e4a795621ae288e1ae52d0fd3a213 on merging branch. Thanks for finding this one!

**Comment by NamecoinGithub** [comment]
Cool, I compiled it fine, and got it past that Block! Nice work, thanks!

However, on LInux Mint it failed to Compile, not sure if you wanna look at it or not!

**Comment by NamecoinGithub** [comment]
![Screenshot at 2024-12-09 19-44-51](https://github.com/user-attachments/assets/f96c7d30-516c-444b-9021-e6d337cf3f24)
![Screenshot at 2024-12-09 19-47-31](https://github.com/user-attachments/assets/5c2d7f76-e969-477e-ab97-f5ccf56367be)

**Comment by VidereLicet** [comment]
Missing include for wallet, if you're not using Legacy use NO_WALLET=1 compile flag, but either way this commit fa57218a88a96e3c26ee25c429ae2211c84f1c2a should resolve that issue.
