### ISSUE TITLE
CLI hangs when mining to remote core

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/LLL-TAO#161]
I was running the 5.1.2 CLI on a ubuntu 20.4 LTS VPS, logged in with the Sessions API, and mining to that wallet.  All would run just fine for some number of hours.  But then after between 10 and 15 hours (estimate), the core would hang.  I would run system/get/info, and the cursor just rudely blinked at me until I hit Ctrl-C.  What I find interesting is that when this happened, the 0.log didn't stop being written to, and the miner didn't throw errors you'd expect when it loses connection to the wallet.  The only way to get the CLI to run again when this happens is to reboot the VPS and rerun ./nexus.  

I tried running the CLI in gdb using -daemon=0, but mining was really messed up when I did that, AND the CLI never hung after 48 or 72 hours.  When I say mining was messed up, what I mean is that the COINBASE transactions never got any confirmations on them, so CREDITs could not be issued against them.  Also, if I refreshed the UI or committed a transaction like sending NXS from the default account to a mining dust account I keep, the COINBASE transactions went away.  Evidence of them was still appearing in the Immature balance, but never anywhere else once they'd gone.  Since the CLI never hung while running the ENABLE_DEBUG=1 version in gdb, I went back to mining normally.  The transactions are handled as they're supposed to be, but I still wait around for the CLI to hang so I can reboot the VPS and log the mining user back in.

**Comment by VidereLicet** [comment]
This is currently an issue inside OpenSSL and related to the SSL code that was first discovered by BEF. I'm currently writing a new portion of the LLC (Lower Level Cryptography) that supports TLS 1.3 so we have our own standalone SSL code working and won't face future issues with OpenSSL such as this.
