### ISSUE TITLE
Recover account

### ISSUE THREAD

**Issue by Brad241** [Nexusoft/LLL-TAO#162]
There appears to be an issue with using the recovery phrase for older users.

I’ve run a test of three separate users whilst using the latest commit (ef876be8502c140e063e610b65d82d90c71e6b0d) and the issue is consistent. 

This is on a private node.

When I create a new user and set a recover – everything is ok. I can change the recovery phrase when logged in and reset password and pin. 

However, when I try to use the recovery phrase of older users (the most recent account tested was created in September 2023), I get error messages. I know the recovery phrase and when using profiles/status/master is confirms a recovery is set.

Error messages received:
When logged out and recovering user: Raw error: {&quot;error&quot;:{&quot;code&quot;:-33,&quot;message&quot;:&quot;Recovery hash mismatch f5fd43429ab0474ea241c00a25417329aef4cff4e9f3e6d164b46196a6afb77d is not 37a54dbc7960989b5ed1d961365eeb0efdbd008ee7cfb1dc27ced346ebb3582a&quot;},&quot;info&quot;:{&quot;method&quot;:&quot;profiles/recover&quot;,&quot;status&quot;:&quot;active&quot;,&quot;address&quot;:&quot;34.213.180.20:57136&quot;,&quot;latency&quot;:&quot;4779.239945 ms&quot;}}

When logged in and changing recovery: 
Raw error: {"error":{"code":-32,"message":"Failed to accept. \u001b[1mAccept\u001b[0m : tx 0119b9be927062064703 REJECTED: \u001b[1mConnect\u001b[0m : invalid signature chain credentials"},"info":{"method":"profiles/update","status":"active","address":"54.202.14.105:44880","latency":"13819.976487 ms"}}

**Comment by Brad241** [comment]
Following further testing, the additional findings have been found:

For some users the issue is resolved within 12 hours. Testing the same credentials and parameters the following day resulted in successful recoveries.
For some users, the issue persists.

After additional checks, the issue is not related to special characters in the recovery phrase.

**Comment by VidereLicet** [comment]
Fixed with commit fa4213396f4dbe52402b8f3eec57d74cb2890d4f
