### ISSUE TITLE
COINBASE CREDITs from mining no longer automatically claimed

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/LLL-TAO#163]
wallet: 3.1.2
OS: Windows
remote core: 5.1.3-rc3

Ever since the weekend when the prime channel mining difficulty went haywire, the notifications from mining (e.g., COINBASE CREDITs) have not been getting claimed.  The COINBASE transactions are recorded fine in the transaction module, but the CREDITs only show up as unclaimed amounts.  In order to claim them, I have to manually run the finance/credit/account API.  They do all credit using that method, but it's odd that the core doesn't process those CREDITs automatically anymore.

**Comment by NealHelman** [comment]
BTW, this is with a local session created on the CLI and the session unlocked for mining and notifictions.

**Comment by Radient4751** [comment]
These transactions do show up in profiles/notifications/master

**Comment by VidereLicet** [comment]
Yes indexes look good, just need to track what is failing in the notifications processor. Should have this fixed later today, will post a commit here when it is done.
