### ISSUE TITLE
Can't adjust staking rewards to zero

### ISSUE THREAD

**Issue by Jugalug123** [Nexusoft/LLL-TAO#164]
When I change my stake rewards to zero my trust account won't mine the next block.
I normally mine 7 trust blocks a day.
I noticed when I change stake rewards to zero my rewards change from 3% to 0.5% instantly.
I'm guessing this should be changed once the next trust block is mined.
The wallet version I am using is;
Wallet version: 3.1.1 beta 9 
Core versions: 5.1.1-rc15
But I also tried it with the latest version and it didn't work either.

I ended up solving the issue by downloading wallet version 3.0.6.
I adjusted the stake rate to zero and I mined the next block in about 4hrs.
I now have access to all my coins.

**Comment by VidereLicet** [comment]
When you adjust your stake rate it will drop your stake power based on your new stake value (which in your case was 0), there was no change to the staking code from 5.0.6 to 5.1.1, any changes would require a hard fork. How long did you try to stake using 5.1.1 and setting it to zero?

**Comment by Jugalug123** [comment]
My stake reward was at 3% I'm not sure how long I was staking with 5.1.1 it must have been a few months.
I ended up uninstalling 5.1.1 and reinstalling 3.0.6. That allowed me to adjust the stake reward to zero.
