### ISSUE TITLE
Not Indexed Error - Now Need to Manually Credit

### ISSUE THREAD

**Issue by S4X1** [Nexusoft/LLL-TAO#168]
I have an error showing a 20 alphanumeric reference is not indexed. It repeats over and over in the logs. Since this occurred, if I have a coinbase transaction it will sit in the unclaimed pool until manually credited. 

This appears to have occurred after my node seemed to have forked away from the main chain by itself. This caused every block found to be rejected by other nodes. I backed up the blockchain data and then did a bootstrap to get back in sync with other nodes and then blocks were once again accepted by the network.

Another separate issue is that it is impossible to sync a node from block 0 any longer. You have to use the bootstrap which is highly centralized. A decentralized project should allow any user of the protocol to sync to the current block from block 0 and participate in the network without relying on a centralized bootstrap as the solution.

Thank you for addressing this.

**Comment by S4X1** [comment]
It appears that I was able to remove this error in the log by running the command ledger/submit/transaction data=(the alpha numeric code from my log which appears to be an old transaction in my .nexus file) after going back to my original blockchain data in the .nexus file. 

I am still testing to see if this transaction will actually get confirmed by the network.

Is there a command to remove this transaction from being broadcast? 

In case it gets stuck it would be good to revert it.

Also testing to see if future coinbase will require manual crediting or if this will now happen automatically as it should.

@VidereLicet thank you for taking the time to look at this.

**Comment by S4X1** [comment]
Is this a transaction that is having an issue being submitted to the network possibly? @VidereLicet

**Comment by NamecoinGithub** [comment]
Yes, I still cannot Sync using Linux Wireguard................I think they are working on a Global Sync Key that each user uses like a Verify Signature Crypto or something I am not sure exactly!

That is interesting that you cannot Sync either however unless using Database, which I also refuse to do!  I Demand to be able to Sync from Scratch for any Blockchain I use time and effort towards, and most of the Time the Rothschild Paid Trolls win the race and destroy the Blockchain!

Stick with me, and hopefully we can Recover Together, as I will NEVER Sell any if I am Pan-Handling in the Arctic!

I haven't got the ability to Sync without using a VPN to test if it will Sync using default ISP IP addy either!  Firewall ect!

**Comment by NamecoinGithub** [comment]
https://github.com/Nexusoft/NexusInterface/issues/240

It might be related to this Issue of Lack of Mining Decentralization!

**Comment by NealHelman** [comment]
I think I fixed my manual crediting issue.  I'm using 5.1.4-rc2, but I imagine it'll work on earlier versions of 5.1.x as well.  I rebuilt the core (I run a remote cover for mining on an ubuntu 20.4 LTS VPS), deleted all the _* directories in the .Nexus directory, and reload the database from bootstrap.  Did that yesterday, and when I woke up this morning, all my COINBASE CREDITs had automagically processed.  I still have that block can't be indexed error all over my 0.log, so I don't think they're related.

**Comment by VidereLicet** [comment]
I need to go through the indexing code and do a cleanup of it, we shouldn't need to delete the _API folder to keep credits flowing. Let me know if you have the issue again @NealHelman

**Comment by NealHelman** [comment]
I actually do still have this issue still.

**Comment by VidereLicet** [comment]
@NealHelman next time you have it please do not reset your database state and get me access to your mining node for me to debug. Unfortunately I need to have this state to find it. Closing this issue until I get this made available.
