### ISSUE TITLE
5.1.3+ Create recovery phrase fails with Cannot Read Crypto Register

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/LLL-TAO#171]
Since 3.1.2 interface, it appears that an error occurs when creating a recovery phrase.  The error indicates that the crypto register cannot be read.  This seems to be preventing the core from subsequently processing transactions.  Attaching 0.logs from two users who reported the issue, as well as the error message display in the wallet.
[0_VOC.log](https://github.com/user-attachments/files/17735120/0_VOC.log)
[0_IM2.log](https://github.com/user-attachments/files/17735122/0_IM2.log)
![VOC_cannot_read_crypto_register](https://github.com/user-attachments/assets/e6a4928a-c42b-45c0-a5d7-d784abd65b58)

**Comment by VidereLicet** [comment]
Have we sorted out this issue?

**Comment by NealHelman** [comment]
I think we'll have to see if we get any reports of it with absolutely-new new users.

**Comment by VidereLicet** [comment]
Okay, keep me posted on this

**Comment by VidereLicet** [comment]
Closing this until we confirm it is still an issue.

**Comment by NealHelman** [comment]
I get the same error in my 0.log after changing the password/PIN.  v5.1.4
[0_JanorSlichter.log](https://github.com/user-attachments/files/18128138/0_JanorSlichter.log)
