### ISSUE TITLE
broadcast tx failed for version 5.1.4 return NOT AVAILABLE IN THIS RELEASE

### ISSUE THREAD

**Issue by glant509** [Nexusoft/LLL-TAO#172]
update node to the lastest version at https://github.com/Nexusoft/LLL-TAO/releases/tag/5.1.4,
broadcast rawTx: 
{"jsonrpc":"2.0","id":2,"method":"sendrawtransaction","params":["02000000f32c52670108147f77a36aa9542a4e95e3aaa78364ce6fa84af02ef927790cdb550e03c0070a6e703cfeab1e4c8b6fb5bbcb1dc1abe1c71dacfd00c3d96f33e1d73714280200000000e44c983081940248034a485ffe32d1d0a6073ba5d154e47d9eaddac4553f4a7bb4b3e0dda789488b71ab29cd19de2af570ee84130428973211d0444db15a242df7ace2147ab5e697a12daba2b2e365fe024801c2e18d1b155dbcff58d85df6135f9988892627b8c62a735e57e4e01e55d6ef379a992a43024cd2de62972e0d7fd14f8253c5f7afed2bfe322e94ddcf4abfc191a17414b4a7d39901490205e9931fc15c21f2bee4e38b73b42cbe939c37b67d23b179816f9f1d473139b4d840f622014c9781f082a872802b2cbb0ecbf9d5dd763d2085f2a9a593416fab0215f5954fcffdbfffffffff02802ac53a00000000222067518f7c7a55717059da9e3f984ad1da2894c2bcec915d0e8f15b3ea7d8e67d66a606d230f000000002576a9200617065af7279719fb6da74d4eae759aa363994b6d57daadf4a9011b128b334688ac00000000"]}
response body is: 
{
    "result": "NOT AVAILABLE IN THIS RELEASE",
    "error": null
}
what's wrong?

**Comment by VidereLicet** [comment]
Ah, looks like an old RPC command that was never finished, we are deprecating the RPC server soon so have you tried to use the API? Legacy UTxO will be removed at some point in the near future so make sure you're not building anything using the RPC console unless you want to change to the API when we deprecate Legacy UTxO. If you really need this command I can activate it for you, but I highly recommend for you to try using the API.

**Comment by glant509** [comment]
Thank you, in fact, I use the rpc api not commond, the node is build by myself use the latest version,  this is my full request :
curl --location 'http://xxxxxxx:9336' \
--header 'content-type: application/json' \
--header 'Authorization: ***********' \
--data '{"jsonrpc":"2.0","id":2,"method":"sendrawtransaction","params":["02000000f32c52670108147f77a36aa9542a4e95e3aaa78364ce6fa84af02ef927790cdb550e03c0070a6e703cfeab1e4c8b6fb5bbcb1dc1abe1c71dacfd00c3d96f33e1d73714280200000000e44c983081940248034a485ffe32d1d0a6073ba5d154e47d9eaddac4553f4a7bb4b3e0dda789488b71ab29cd19de2af570ee84130428973211d0444db15a242df7ace2147ab5e697a12daba2b2e365fe024801c2e18d1b155dbcff58d85df6135f9988892627b8c62a735e57e4e01e55d6ef379a992a43024cd2de62972e0d7fd14f8253c5f7afed2bfe322e94ddcf4abfc191a17414b4a7d39901490205e9931fc15c21f2bee4e38b73b42cbe939c37b67d23b179816f9f1d473139b4d840f622014c9781f082a872802b2cbb0ecbf9d5dd763d2085f2a9a593416fab0215f5954fcffdbfffffffff02802ac53a00000000222067518f7c7a55717059da9e3f984ad1da2894c2bcec915d0e8f15b3ea7d8e67d66a606d230f000000002576a9200617065af7279719fb6da74d4eae759aa363994b6d57daadf4a9011b128b334688ac00000000"]}'
I found this problem after I upgrade the node version

**Comment by VidereLicet** [comment]
Are you using Legacy transactions or the Tritium Protocol? Also what version have you upgraded from?
