### ISSUE TITLE
Unable to Sync From Block 0 - Stuck at Block 342,615

### ISSUE THREAD

**Issue by S4X1** [Nexusoft/LLL-TAO#173]
This is still an existing issue on release 5.1.4 and it creates a centralized protocol due to a central point of failure. Why are we removing unresolved issues @VidereLicet ? A decentralized blockchain should never rely on a bootstrap for nodes to sync.

**Comment by VidereLicet** [comment]
Compile from merging, this was resolved after the release of 5.1.4 with commit 63e240ce2c5e4a795621ae288e1ae52d0fd3a213 and will be released with the next version of the wallet.
