### ISSUE TITLE
v5.1.4 - Error adjusting stake amount with manual alteration of amount

### ISSUE THREAD

**Issue by NealHelman** [Nexusoft/LLL-TAO#175]
Interface 3.1.5
Core 5.1.4

User clicked "Max Amount" then manually adjusted the amount.  The example he provided was manually adjusting the adjustment amount from 151.56746 to 150.99746.  This is a random example, not actual amounts used.

I found the error message that was thrown visibly to the user, "[1mset_value [0m : Parameter can only have decimal places" in the src/Util/types/precision.h file.  I don't know if it's an issue with this file, or with what the wallet is sending.

User subsequently reported to me that he increased to Max Amount without manually adjusting the adjustment value, and the stake balance adjustment entry process working without any error.

Attached 0.log and screenshot user provided of error.  
[0_peterh_20241214.log](https://github.com/user-attachments/files/18137912/0_peterh_20241214.log)
![stake_adjust_error_2024-12-14](https://github.com/user-attachments/assets/b5d9e6e6-0423-45dd-8e72-a347de465ba1)

**Comment by VidereLicet** [comment]
This should be in NexusInterface, it is a front-end issue.
