### ISSUE TITLE
Server-side filters for transactions listing

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#46]
Server-side filters for transactions listing.

Currently the desktop wallet is having to load ALL the transactions and use client-side filtering. This is not scalable, especially on mobile (that's why currently mobile wallet hasn't enabled transactions filter yet). The current generic filter system isn't robust enough to support the filter functionalities needed on the frontend.

So we need users/list/transactions to accept the following parameters (may be grouped inside an object):
- `operations`: an array of operations to include in the result
- `timespan: { from, to }`: the range of transaction timepsan to accept
- `account`: Ideally accepts both account name and account address, and the backend should resolve it to either name or address. Otherwise, should be divided to `account_address` and `account_name`
- `token`: Ideally accepts both token name and token address, and the backend should resolve it to either name or address. Otherwise, should be divided to `token_address` and `token_name`
- The current `offset` and `limit` parameters should still work as usual for the pagination to work

The returned output needs to include the following (in addition to the item list):
- Total number of results (without `offset` and `limit` parameters). This is useful for the front end to display the total number of pages 

Because it needs a different output schema, you may consider adding a new API called users/search/transactions.

**Comment by VidereLicet** [comment]
This should do the trick, right now it's only piped for objects and results, but I'm getting to transactions next so it should be good to go for you within a week or two tops:

https://github.com/Nexusoft/LLL-TAO/blob/merging-harden/docs/API/QUERIES.md
