### ISSUE TITLE
After Adjusting stake amount the pending stake change disappears after few minutes.

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#47]
When a adjust stake amount request is submitted, the pending stake change is seen in the staking details and disappears in a minute or two and upon repeating the adjust stake, the same things happens over and over. This makes it impossible to adjust the stake amount for the user as the request gets reject after a few minutes.

This issue is remedied only after changing password and PIN and logging in with the new credentials. This issue has been faced by a few users.

**Comment by VidereLicet** [comment]
Excellent, thank you for reporting this issue. We will add it to the buglist!

**Comment by Aeonwise** [comment]
> Excellent, thank you for reporting this issue. We will add it to the buglist!
This is the error message in the log:    " ERROR: FindStakeChange : Stake Minter: Invalid public key on stake change request...removing"
