### ISSUE TITLE
Notification processor not crediting incoming transactions

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#48]
Found some desktop wallet users transactions specially from legacy to tritium have not been credited to their accounts. Have checked and found the transaction is on blockchain and the address is correct. Asked the user to credit transactions manually, and it failed.

Temporary workaround for this issue:
1. Close wallet, In the core data folder rename  _TRUST any other name. Start the wallet, which credits the transaction. Close wallet and rename _TRUST to its original name.
2. Use the beta mobile wallet and login using the same user credentials credits the transaction. (core version 5.1)

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by VidereLicet** [comment]
Resolved with commit f29721841c89447978500713d2c807b7826de5cb
