### ISSUE TITLE
When nexus.conf is parsed it doesn't ignored commented lines

### ISSUE THREAD

**Issue by bibbityjibbity** [Nexusoft/LLL-TAO#5]
When lines are commented out with # in config file, the wallet still adds them to map and prepends them with -. I believe you should be able to fix it by changing this line:
https://github.com/Nexusoft/LLL-TAO/blob/26a5dcd96ac66ee0f29f3c5bcdec7c2ad88329fa/src/Util/config.cpp#L44

To
            `if(i == std::string::npos || line.front() == '#')`

**Comment by scottsimon36** [comment]
This has already been updated via commit:
https://github.com/Nexusoft/LLL-TAO/commit/a7a4c4a36f6aa9ccd0544352c8ac2def3d228a27

to be included in release 3.0.2
