### ISSUE TITLE
producer timestamps rejected when mining with long gap between blocks

### ISSUE THREAD

**Issue by ahatstat** [Nexusoft/LLL-TAO#54]
When mining the hash channel on a testnet by myself on core version 5.03 I noticed that if I 

request a block
wait 1 hour (no new blocks are mined)
request a block
submit block

The block will be rejected - ERROR: Check : producer transaction timestamp is too early.  
Requesting a new block does not resolve the problem.   I found this by running NexusMiner V2.0 branch using a CPU or FPGA worker.  When I stop mining and rerun the miner an hour later I see this error.  I can resolve this by restarting core.  Perhaps there is an issue with stale producer timestamps in the block cache.

**Comment by VidereLicet** [comment]
Do you see any new work coming to the miner once you re-request it after an hour? Or do you stop getting work as well?

**Comment by ahatstat** [comment]
Yes I get new work when requested.  Attached is a log.  Maybe there is a clue in there.  Search for "new_block" and "producer transaction timestamp is too early". 
[producer_timestamp_too_early.log](https://github.com/Nexusoft/LLL-TAO/files/6635523/producer_timestamp_too_early.log)

**Comment by VidereLicet** [comment]
Oh I think I know what the issue could be, we cache the producer transaction so you don't need to rebuild the keys and signatures with Argon2 more than once per round, which can be time consuming, so I bet the cache isn't being cleared based on that rule, will post commit here when fixed

**Comment by VidereLicet** [comment]
This is resolved with commit 6b844ddbb0617d827a88f1aa44162702eed507ed

**Comment by ahatstat** [comment]
I confirmed the issue is resolved.
