### ISSUE TITLE
Assets/update/asset fieldname error

### ISSUE THREAD

**Issue by Brad241** [Nexusoft/LLL-TAO#55]
When using the fieldname "balance" and make it mutable, the API returns the following response when attempting to update: 
{"code":-30,"message":"Operations failed to execute. \u001b[1mBuild\u001b[0m : OP::WRITE: cannot generate post-state"}}

**Comment by VidereLicet** [comment]
Yes, the balance field is a reserved field so you aren't able to update it, but you are able to generate a new register with that field. This is being fixed for 5.1 release, thank you for reporting!
