### ISSUE TITLE
Windows - Wallet doesn't react to GET_HEIGHT mining message after a block got accepted

### ISSUE THREAD

**Issue by beuschl** [Nexusoft/LLL-TAO#60]
WIndows, Wallet CLI 5.0.5 (master), Testnet 2

When mining against the wallet there are some rara cases that after establishing a connection the wallet doesn't react to GET_HEIGHT mining messages (the TCP pakets are there, controlled by wireshark). Only a reconnection to wallet solves this

Then there is the case that the wallet reacts normally to GET_HEIGHT with BLOCK_HEIGHT like expected. But after a block got submitted to the wallet (and an ACCEPT message have been received), the wallet doesn't react to GET_HEIGHT anymore (again on network the TCP pakets are there and also the ACK messages). 
Only a reconnect to the wallet solves this

**Comment by VidereLicet** [comment]
Thank you for reporting this, I'm redoing the notifications system currently (Users API is last to finish) so when this is complete I will be sure to let you know
