### ISSUE TITLE
Invoice API total amount calculated by multiplying unit cost and units is faulty

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#61]
Wallet Version:3.0.6
Core version: 5.0.5
Invoice module:1.0.5
OS: mac on M1
While paying invoices found that there is difference between the amount invoiced and amount payed out. When i checked found the amount calculated by API is faulty and the same is payed out. 
http://api.nexus.io:8080/invoices/get/invoice?address=831XWLZSAvYXvvJ7CYWqzYEUiQKFteGcmqdYaHDxsXv2Gyo3Dwx
In the above invoice the unit amount=35.9 and unit=20.18 which should amount=724.462, but the API calculated it as 719
This has effected all the invoices.

**Comment by VidereLicet** [comment]
This above needs some changes, we want to extract integers and avoid doubles as much as possible. If you ever do take a double you need to convert to integer to do the math otherwise you will get rounding errors
