### ISSUE TITLE
Finance API merging branch not showing DEBIT transactions

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#62]
Found the merging branch 5.1-rc2 finance API not showing DEBIT transactions

http://api.nexus-interactions.io:8080/finance/transactions/account?address=8CpTP5hwX3nW1Ap5Z3bp1vUkkiq1cbNVcPVXAWEwnRKGsXF9xEg
The finance transaction for this token account only lists 5 transaction records

http://api.nexus-interactions.io:8080/finance/history?address=8CpTP5hwX3nW1Ap5Z3bp1vUkkiq1cbNVcPVXAWEwnRKGsXF9xEg
When you check the same account history there are 7 history records

The 2 DEBIT transactions are not shown with the finance/transactions call
Also checked https://explorer.nexus.io/search?search=8CpTP5hwX3nW1Ap5Z3bp1vUkkiq1cbNVcPVXAWEwnRKGsXF9xEg

**Comment by VidereLicet** [comment]
DEBIT transactions do not modify the receivers account, they are only modifying the senders account so they are not transactions that have happened to a given register, only the CREDIT on receive and the DEBIT on send. This is part of the dual accounting system, you see the transactions that modified your register, not foreign events that are used to modify the register (DEBIT -> CREDIT). Only the CREDIT modifies your account, the DEBIT modifies the sender's account.
