### ISSUE TITLE
Asset Incoming CLAIM transactions, auto claim in wallet and deducts fee automatically, can be used to drain wallets without the users authorization

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#63]
Desktop wallet 3.0.6, Core 5.0.5

When sending assets to a user wallet, the asset will be auto claimed by the wallet and the associated fee is deducted. This can be used as a means to drain a users wallet without his knowledge and authorization.

Request to provide a mechanism for incoming CLAIM transactions where fee is auto debited to be controlled by the user. This will prevent misuse.

Find attached the tx details:
Transaction ID: https://explorer.nexus.io/search?search=0101b84de353a81870f2bcb996c5b6f6f5b083f418a0a3ea94c7d3c2582318bc0ff655b7fd1f05a7447c5dfff6a12dd1f977822f53b3161dc63b8446edb5b7ca

**Comment by VidereLicet** [comment]
The feature of creating a name record when receiving a transfer has been disabled with 5.1
