### ISSUE TITLE
Accounts Section causes issues having Tokens listed with NXS receive addresses

### ISSUE THREAD

**Issue by Gapcoin1** [Nexusoft/LLL-TAO#68]
Hi,

I just ran into this issue, having the tokens address listed as a NXS address under Accounts is easy to make mistake and use it as a receive address for exchanges or other........

All token accounts should be segregated into the Tokens tab

This will prevent any non NXS receive address accounts from showing in the Nexus Interface Accounts section.........

Either that or provide Colored Addresses to instead of the small print Tokens label for Accounts types

**Comment by VidereLicet** [comment]
This should be submitted on wallet interface repository, this is the TAO backend
