### ISSUE TITLE
Add New Feature in nexus conf to use Higher Bit Falcon Encryption

### ISSUE THREAD

**Issue by Gapcoin1** [Nexusoft/LLL-TAO#69]
Add nexus.conf to use higher bit Quantum Falcon 1024

Create an extra nexus.conf feature to allow Falcon1024

falcon1024=1

**Comment by VidereLicet** [comment]
This would require a hard fork for other nodes to recognize the higher encryption standards, will assess for 6.0

**Comment by Gapcoin1** [comment]
Cool Thanks
