### ISSUE TITLE
Anonymize Nexus Address Owners from a Sigchain! 

### ISSUE THREAD

**Issue by Gapcoin1** [Nexusoft/LLL-TAO#70]
**Anonymization of Nexus Owner field for new Addresses under a Sigchain!**

@VidereLicet 

This would be a good time to open the debate of Anonymization and Security!  Zcash probably has good ideas using ZK-Snarks to generate linkable addresses under a Sigchain

It should not be possible to track every address created under a Sigchain, a Sigchain owner should be the only person able to see all the created addresses owned by that Sigchain!

As it is the Owner address is the same for each created NXS address under a Sigchain! 

This is found in the Owner field in the Nexus Block Explorer and can track each address created by a Sigchain easily!

**https://explorer.nexus.io/

**Comment by Gapcoin1** [comment]
I view this as a huge issue to be honest!

**Comment by VidereLicet** [comment]
You can create multiple sigchains if you want to separate your assets, or wait until profiles is done so it can be done automatically but by nature of the design you can't hide the genesis-id of a sigchain, as this is used to authenticate the register ownership.
