### ISSUE TITLE
To remove the use of ":" in usernames, names and namespaces

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#71]
I can create an account with "test:", it has a colon at the end. This becomes an issue when using to send or receive nxs with the username:account.  "test::default" is not recognised and this will create an issue going forward.
![IMAGE 2022-02-02 19:04:21](https://user-images.githubusercontent.com/84140911/152163801-ecef8a2a-0416-44f0-9245-aaebcf365149.jpg)

**Comment by KenCorma** [comment]
So I have been looking into this and the issue stems from they way we extract that name/namespace/account from the input. 

Your example it is treating test as a namespace and default as a username as it sees the `::` 

There is not technical reason why we can not have the `:` in the username as if I manually run 

>                 hashNamespace = TAO::Ledger::SignatureChain::Genesis(SecureString("test:"));
>                 fFound = TAO::Register::GetNameRegister(hashNamespace, "default", nameObject);
>                 hashNameObject = TAO::Register::Address("default", hashNamespace, TAO::Register::Address::NAME);

I will get the correct data. 

This code comes from `src/TAO/API/commands/names/names.cpp` as part of the GetName method. 

I am not sure the best way to go about this, how do you determine when the nexus separators start and end and where does the user's input start and end. 

If you input `test::default` 
is test: the username and default the account
or is test the username and :default the account
OR is test the namespace and default the username

that example shows 3 possible outcomes from the same text. 

We could force the non-use of `:` but this would be a restriction based on understanding the input, not by an technical issue.

**Comment by VidereLicet** [comment]
Issue is being retroactive to all possible name types, there are some that have a colon in them and making a direct rule to this can break the previous ones
