### ISSUE TITLE
Need an API to verify the tokens representing an asset is actually the tokenized ones for a user who plans to buy.

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#73]
There is no way for a user who wants to buy part of a tokenized asset, to confirm that the token he is buying is actually the tokens which represent that particular asset. This verification is very important for third user who wants to buy tokens representing an asset and he would like to verify before buying, and also before listing on P2P exchange.

An asset/verify or Register/asset/verify API which can used by third party and not only the owner is needed to verify any tokenised asset. It should list the asset details and the linked tokens.

**Comment by VidereLicet** [comment]
This is complete with commit 94496d1677626cc481b34cf0542957677839bcf3

The command endpoint is:
assets/verify/partial token=<name or address>

It will then return valid = true and an asset key with info on the asset that is owned by this token.
