### ISSUE TITLE
Transferring Global Name to different user, Still points to old Address

### ISSUE THREAD

**Issue by Gapcoin1** [Nexusoft/LLL-TAO#74]
Transferring a Global name works now to a username, however the Point to Address when global name was created still points to the old address and all transactions still direct to the old address!

**Comment by VidereLicet** [comment]
This isn't updated, because you have no idea what they will change address to once received.

**Comment by Gapcoin1** [comment]
The person who buys it should provide the Point to Address as well as the Username to transfer to

It does not as far as I can find a way to update the Point to Address after transfer to a different user

This has to be done from the original owner sending

I have tested this myself transferring it between myself so I know it doesn't work and it's still an error
