### ISSUE TITLE
"Unsupported type for name/address" for trust accounts

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#75]
finance/get/account is returning error -49 "Unsupported type for name/address" for trust accounts. 

Although under the hood, trust accounts might be a bit different than normal accounts, but from an API user's standpoint, they all look the same (all listed under finance/list/accounts) and therefore need to behave the same. Otherwise a new concept for trust accounts needs to be introduced to distinguish it from normal accounts (with a new name, new API endpoints etc...)

**Comment by VidereLicet** [comment]
finance/get/trust or finance/get/any will allow you lookup for correct type, or for any type
