### ISSUE TITLE
The command '/bin/sh -c mkdir /lispers.net; cd /lispers.net; curl --insecure -L $LISP_URL | gzip -dc | tar -xf -' returned a non-zero code: 2

### ISSUE THREAD

**Issue by Mattiell0X** [Nexusoft/LLL-TAO#79]
When trying to run docker, I get the error below! Can someone help me?

https://i.imgur.com/5i2H4qN.png

Setting up python3-zbar:amd64 (0.23.90-1) ...
Setting up python3-qrtools (2.0~bzr33-2) ...
Processing triggers for libc-bin (2.31-13+deb11u3) ...
Processing triggers for mailcap (3.69) ...
Removing intermediate container 30d69820f6a8
 ---> 4f1788dc6eff
Step 6/33 : RUN mkdir /lispers.net; cd /lispers.net; curl --insecure -L $LISP_URL | gzip -dc | tar -xf -
 ---> Running in a5788a19f688
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   139    0   139    0     0    187      0 --:--:-- --:--:-- --:--:--   187
100  1144  100  1144    0     0   1076      0  0:00:01  0:00:01 --:--:--  1076

gzip: stdin: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
The command '/bin/sh -c mkdir /lispers.net; cd /lispers.net; curl --insecure -L $LISP_URL | gzip -dc | tar -xf -' returned a non-zero code: 2
root@apiblock:/home/apiblock/LLL-TAO# mkdir /lispers.net; cd /lispers.net; curl --insecure -L $LISP_URL | gzip -dc | tar -xf -
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

gzip: stdin: unexpected end of file
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

**Comment by NeuroBanco** [comment]
Hi, Thanks for the link!

I did the following, copy this link and put it in the Dockerfile file and had it run again.
Unfortunately it gave the same error!

**Comment by farinacci** [comment]
Can you point me to the Dockerfile you are using and l’ll give it a try?

Dino

**Comment by NeuroBanco** [comment]
https://github.com/Nexusoft/LLL-TAO/blob/merging/Dockerfile

I'm running this...
See I had to manually install the dependency
line 41 libssl1.0-dev
That's because not just any font has this file. here it was.

Another thing to resolve is that they must change this filename

   line 47: python-qrtools for this python3-qrtools

**Comment by farinacci** [comment]
The Dockerfile will need to be modified. Later releases of the lispers.net code allows both python2.7 and python3 so there are new libraries required. I'll spend some time on this and send you a diff.

If you want to know the new build requirements, you can check out the Dockerfile in the lispers.net repo here:

    https://github.com/farinacci/lispers.net/blob/master/build/Dockerfile

Dino

**Comment by NeuroBanco** [comment]
Wow thank you very much! Tomorrow I will test!

**Comment by farinacci** [comment]
Just checking in. Did you make any progress on this?

Cheers,
Dino

**Comment by VidereLicet** [comment]
Have updated internal Dockerfile to current LISP file, moved to lisp directory:

https://github.com/Nexusoft/LLL-TAO/commit/7e9027f504f4c10c924b4ffb188520b175233063
