### ISSUE TITLE
Improve the way `sessions/unlock/local` works

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#91]
When I'm having a field, e.g. 'mining', already unlocked, calling `sessions/unlock/local` with another field set to 'true', e.g. staking=true and 'mining' field omitted (`undefined` as in Javascript) makes that 'mining' field locked again. I expected the behavior being as follow: any field set as 'true' should be unlocked, any field set as 'false' should be locked, and any other fields which are omitted or set as 'undefined' should stay as-is

**Comment by VidereLicet** [comment]
Good catch, had a caching issue. It's fixed now (75b1e58fc6e85dd037aac5c202e8113ab9ca3d82)
