### ISSUE TITLE
Add an API that lists logged in sigchains

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#94]
In multiuser mode, the wallet UI needs an API that lists logged in sigchains. Else the wallet has to rely on cached data which is not always in sync especially when using remote core, and increases code complexity. The API could be disabled by default, enabled by a core param.

**Comment by VidereLicet** [comment]
Fine if I list the sessions and genesis? Don't want to give up too much information, don't think it would be good to display the username of all sessions but I could do something like sessions/list/local and give a small status update on those based on the same data that is in sessions/status/local. What do you think?

**Comment by VidereLicet** [comment]
This has been completed with commit 1b1dcbf73fa1d06f1eb7d7edb10facfe1a22e944 this requires you to enable -multiusername and it will also display username in profiles/status without requiring PIN.
