### ISSUE TITLE
Add 'username' back into `sessions/status/local` result

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#95]
Currently we have no way to get the username of a logged in user. The wallet UI has to cache the username whenever user logs in to display it. But it's impossible when using a remote core where user already logged in. The easiest way for the wallet code is to add `username` field back into `sessions/status/local`. If it's a privacy/security concern, it could be disabled by default, and enabled by a core param.

**Comment by VidereLicet** [comment]
You need to supply the pin to generate username due to privacy, just add the session pin and you'll get session specific data that's private

**Comment by Qrysto** [comment]
@VidereLicet It still wouldn't work in case that the wallet UI starts when the core is already in a logged in state (when it's connected to a remote core or when the front end simply refreshes). The front end wouldn't have the PIN to send to `profiles/status/master` because user has already logged in.
