### ISSUE TITLE
Can't debit from trust 

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#96]
When sending NXS from trust account using `finance/debit/account`, I get "Unsupported type for name/address" error. But when I try replacing it with `debit/trust`, the core returns "API Not Found: trust" error.

**Comment by VidereLicet** [comment]
You need to do finance/debit/trust to debit from a trust account, or finance/debit/any and it will allow any type you choose in the debit contract. I just tested and it is all working correctly.

**Comment by Qrysto** [comment]
@VidereLicet Oh turns out it was a front end bug, I fixed it and finance/debit/trust worked as expected
