### ISSUE TITLE
API inconsistency regarding 'any' type

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#97]
Currently `finance/get/any` is available for getting either account or trust (though undocumented), but other APIs where both 'account' and 'trust' are the options (like `finance/transactions/...` or `finance/list/...`) 'any' is not an option. This is an inconsistency and I'd suggest to have an 'any' option for any API that can be used with both 'account' and 'trust'

**Comment by VidereLicet** [comment]
This was specifically designed, I can add in support for finance (40178edd563130f341b717bbf29e9952d0e3eac9). So you know, 'any' debits allow debits from any token type and selects all accounts based on your incoming parameters, 'all' selects from all of your accounts but only supports one token type
