### ISSUE TITLE
Creating token account without a name, created a null name , this is specific to Bubble.

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#98]
This is specific to Bubble, when the API call is created, all the parameters have to be provided and if the user does not want to create a name and leaves the name parameter blank, a null name is created. 

Is it possible to ignore the "name" parameter if it is empty?

{
"owner": "b7fa11647c02a3a65a72970d8e703d8804eb127c7e7c41d565c3514a4d3fdf13",
"version": 1,
"created": 1673851832,
"modified": 1673854423,
"type": "OBJECT",
"register": "8BwLP3DUZ9Awe2dg1SyQQLCdbAcMoYzBLZyiY9qBQxLSv1Vav3Y",
"name": null,
"namespace": "",
"address": "8JPLqFyFDTjpvrey5vXg1ShCAkj8ZSntaz4XHW2DKiUZbtrg3qS"
}, 

<img width="757" alt="Screenshot 2023-01-23 at 7 52 52 PM" src="https://user-images.githubusercontent.com/84140911/214063245-113b9f34-2ce3-42e7-aa91-197056661cc5.png">

**Comment by VidereLicet** [comment]
Fixed with commit abb26aa113bd21e06e7e5b8a878cd975774bc868
