### ISSUE TITLE
`sessions/unlock/local` shouldn't raise error on attempt to unlock an already unlocked option

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#99]
When I call `sessions/unlock/local` with `notifications=true`, for example, when 'notifications' option is already unlocked, I get an "Account already unlocked for notifications" error. I don't think there should be an error in this case, and I expect the API to just gracefully accept the input and successfully complete the call.

**Comment by Qrysto** [comment]
Besides, this endpoint also gives "You must specify at least one unlock action" error when all options are set to false or omitted. This is a smaller issue since it can be worked around with a check before calling the API, but it feels a bit uncessarily strict. It could simply end without an effect.

**Comment by VidereLicet** [comment]
This is resolved with commit 471d9a5183199c942641fae48e4d4f85470ecb12
